spring.application.name=UnitTestApplication
#DB configuration
spring.datasource.url=jdbc:mysql://localhost:3306/unit-test?useSSL=false
spring.datasource.username=root
spring.datasource.password=Pratik@21
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true